/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "1.9.22"
}

repositories {
    mavenLocal()
    mavenCentral()
}

group = "com.github.oliveiradd.dydns"
version = "1.0.0"
description = "dydns"
java.sourceCompatibility = JavaVersion.VERSION_17

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = "17" // Set JVM target version to 17
    kotlinOptions.freeCompilerArgs = listOf("-Xjsr305=strict") // Optional: Configure Kotlin compiler options
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "com.github.oliveiradd.dydns.MainKt" //add Kt after the "Main" class
    }
}

// this is needed regardles of if you're using external libraries - kotlin own libraries are external to java
tasks.withType<Jar>() {
    configurations["compileClasspath"].forEach { file: File ->
        from(zipTree(file.absoluteFile))
    }
}

